version: "3.8"

services:
  backend:
    build:
      context: ./backend # Point to the backend folder
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "sqlite:///./test.db"
    volumes:
      - ./backend:/app/backend
      - ./test.db:/app/test.db
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
